### PR TITLE
Adds support for nested objects and arrays

### PR DESCRIPTION
**Pull request by jmhummel**
Fixes issue #4
Refactored AttributeValue calculation into separate function "sizeOfValue"
Adds support for boolean, list, and map values
Fixes number size calculation: (1 byte per two significant digits) + (1 byte)

### CODE REVIEW

**Comment by jmhummel** [comment]
@mcwhittemore Could you please review my PR? Thank you

**Comment by jmhummel** [comment]
@mcwhittemore Any chance you could take a look at this PR?

**Comment by mcwhittemore** [comment]
@jmhummel - sorry for the slow review here. I've merged this and published it to npm with a small tweak to make sure that buffer objects are handled different from other types of objects.

There was also a small difference in the tests from your PR. The size of a number went down by one. From the code comment this seemed intensional, can you confirm that?

Also, sorry for the slow review here. I'm not sure how I missed this notification. In #6 I set up ci to start running the tests, any chance you can add tests for nested objects and lists in follow on PR?

**Comment by jmhummel** [comment]
@mcwhittemore Yes, I believe the new calculation for numbers is more accurate according to the documentation. I'll work on writing up some tests for nested objects and lists for another PR

**Pull request merged**
